export default {
  MONTHS: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  CUR_DATE: new Date(),
  SLIDER_INTERVAL: 5,
  HOUSE_COORDS: [37.8282608, -0.7899585] as [number, number],
  ZOOM: 13,
  ICON_SIZE: [38, 38] as [number, number],
};
